
name: Cypress e2e tests

on:
  push:
    branches: [master]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12'
      - name: Install dependencies
        run: npm ci
      - name: Start server
        run: npm run dev
      - name: Wait for server to start
        run: |
          timeout 10s bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/localhost/3000; do sleep 1; done'
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          cypress-command: npm run e2e